language: node_js
node_js:
  - "node"

addons:
  apt:
    packages:
    - libgconf-2-4

script: 
 - bash server-run.sh &
 - npm run -s lint
 - npm run -s test
 - npm run -s build

notifications:
    slack: kento75:s4XYtG22oWdRPtYihALclluJ
